name: ci 
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: git config user.name qtdocs-CI
      - run: git config user.email qtdocs@github.com
      - run: git pull
      - run: pip install mkdocs-material 
      - run: pip install mike
      - run: pip install mkdocs-macros-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: mike deploy --push --update-aliases 6.0 latest
#      - run: mike retitle latest (Outdated)
      - run: mike set-default --push latest
      - run: mkdocs gh-deploy --force
